# Generated by Django 5.0.6 on 2024-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unify', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('no', 'Not Approved')], default='w', max_length=2),
        ),
    ]
